language: python
python: 
  - "3.6"
services:
  - mysql
env:
  - DJANGO=2.2 DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database django; GRANT ALL PRIVILEGES ON *.* TO "django"@"localhost" IDENTIFIED BY "password"; flush privileges;' -u root
script:
  - python /src/camerastore/manage.py migrate